// Generated by gencpp from file myPackage/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MYPACKAGE_MESSAGE_ADDTWOINTS_H
#define MYPACKAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <myPackage/AddTwoIntsRequest.h>
#include <myPackage/AddTwoIntsResponse.h>


namespace myPackage
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace myPackage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myPackage::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::myPackage::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::myPackage::AddTwoInts > {
  static const char* value()
  {
    return "myPackage/AddTwoInts";
  }

  static const char* value(const ::myPackage::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::myPackage::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::myPackage::AddTwoInts >
template<>
struct MD5Sum< ::myPackage::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myPackage::AddTwoInts >::value();
  }
  static const char* value(const ::myPackage::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPackage::AddTwoIntsRequest> should match
// service_traits::DataType< ::myPackage::AddTwoInts >
template<>
struct DataType< ::myPackage::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::myPackage::AddTwoInts >::value();
  }
  static const char* value(const ::myPackage::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myPackage::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::myPackage::AddTwoInts >
template<>
struct MD5Sum< ::myPackage::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myPackage::AddTwoInts >::value();
  }
  static const char* value(const ::myPackage::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPackage::AddTwoIntsResponse> should match
// service_traits::DataType< ::myPackage::AddTwoInts >
template<>
struct DataType< ::myPackage::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::myPackage::AddTwoInts >::value();
  }
  static const char* value(const ::myPackage::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPACKAGE_MESSAGE_ADDTWOINTS_H
