// Generated by gencpp from file mypackage/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MYPACKAGE_MESSAGE_ADDTWOINTS_H
#define MYPACKAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <mypackage/AddTwoIntsRequest.h>
#include <mypackage/AddTwoIntsResponse.h>


namespace mypackage
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace mypackage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mypackage::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::mypackage::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::mypackage::AddTwoInts > {
  static const char* value()
  {
    return "mypackage/AddTwoInts";
  }

  static const char* value(const ::mypackage::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::mypackage::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::mypackage::AddTwoInts >
template<>
struct MD5Sum< ::mypackage::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mypackage::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypackage::AddTwoIntsRequest> should match
// service_traits::DataType< ::mypackage::AddTwoInts >
template<>
struct DataType< ::mypackage::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::mypackage::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mypackage::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::mypackage::AddTwoInts >
template<>
struct MD5Sum< ::mypackage::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mypackage::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypackage::AddTwoIntsResponse> should match
// service_traits::DataType< ::mypackage::AddTwoInts >
template<>
struct DataType< ::mypackage::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::mypackage::AddTwoInts >::value();
  }
  static const char* value(const ::mypackage::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPACKAGE_MESSAGE_ADDTWOINTS_H
