// Generated by gencpp from file myPackage/BadTwoInts.msg
// DO NOT EDIT!


#ifndef MYPACKAGE_MESSAGE_BADTWOINTS_H
#define MYPACKAGE_MESSAGE_BADTWOINTS_H

#include <ros/service_traits.h>


#include <myPackage/BadTwoIntsRequest.h>
#include <myPackage/BadTwoIntsResponse.h>


namespace myPackage
{

struct BadTwoInts
{

typedef BadTwoIntsRequest Request;
typedef BadTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BadTwoInts
} // namespace myPackage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myPackage::BadTwoInts > {
  static const char* value()
  {
    return "60962375a49bd6746d7c85dff75ebb9c";
  }

  static const char* value(const ::myPackage::BadTwoInts&) { return value(); }
};

template<>
struct DataType< ::myPackage::BadTwoInts > {
  static const char* value()
  {
    return "myPackage/BadTwoInts";
  }

  static const char* value(const ::myPackage::BadTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::myPackage::BadTwoIntsRequest> should match
// service_traits::MD5Sum< ::myPackage::BadTwoInts >
template<>
struct MD5Sum< ::myPackage::BadTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myPackage::BadTwoInts >::value();
  }
  static const char* value(const ::myPackage::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPackage::BadTwoIntsRequest> should match
// service_traits::DataType< ::myPackage::BadTwoInts >
template<>
struct DataType< ::myPackage::BadTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::myPackage::BadTwoInts >::value();
  }
  static const char* value(const ::myPackage::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myPackage::BadTwoIntsResponse> should match
// service_traits::MD5Sum< ::myPackage::BadTwoInts >
template<>
struct MD5Sum< ::myPackage::BadTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myPackage::BadTwoInts >::value();
  }
  static const char* value(const ::myPackage::BadTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPackage::BadTwoIntsResponse> should match
// service_traits::DataType< ::myPackage::BadTwoInts >
template<>
struct DataType< ::myPackage::BadTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::myPackage::BadTwoInts >::value();
  }
  static const char* value(const ::myPackage::BadTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPACKAGE_MESSAGE_BADTWOINTS_H
