// Generated by gencpp from file myPackage/BadTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef MYPACKAGE_MESSAGE_BADTWOINTSRESPONSE_H
#define MYPACKAGE_MESSAGE_BADTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myPackage
{
template <class ContainerAllocator>
struct BadTwoIntsResponse_
{
  typedef BadTwoIntsResponse_<ContainerAllocator> Type;

  BadTwoIntsResponse_()
    : sum(0)  {
    }
  BadTwoIntsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BadTwoIntsResponse_

typedef ::myPackage::BadTwoIntsResponse_<std::allocator<void> > BadTwoIntsResponse;

typedef boost::shared_ptr< ::myPackage::BadTwoIntsResponse > BadTwoIntsResponsePtr;
typedef boost::shared_ptr< ::myPackage::BadTwoIntsResponse const> BadTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myPackage::BadTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::myPackage::BadTwoIntsResponse_<ContainerAllocator1> & lhs, const ::myPackage::BadTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::myPackage::BadTwoIntsResponse_<ContainerAllocator1> & lhs, const ::myPackage::BadTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace myPackage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::myPackage::BadTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myPackage/BadTwoIntsResponse";
  }

  static const char* value(const ::myPackage::BadTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
"\n"
;
  }

  static const char* value(const ::myPackage::BadTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BadTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myPackage::BadTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myPackage::BadTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYPACKAGE_MESSAGE_BADTWOINTSRESPONSE_H
