// Generated by gencpp from file mypackage/BadTwoInts.msg
// DO NOT EDIT!


#ifndef MYPACKAGE_MESSAGE_BADTWOINTS_H
#define MYPACKAGE_MESSAGE_BADTWOINTS_H

#include <ros/service_traits.h>


#include <mypackage/BadTwoIntsRequest.h>
#include <mypackage/BadTwoIntsResponse.h>


namespace mypackage
{

struct BadTwoInts
{

typedef BadTwoIntsRequest Request;
typedef BadTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BadTwoInts
} // namespace mypackage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mypackage::BadTwoInts > {
  static const char* value()
  {
    return "60962375a49bd6746d7c85dff75ebb9c";
  }

  static const char* value(const ::mypackage::BadTwoInts&) { return value(); }
};

template<>
struct DataType< ::mypackage::BadTwoInts > {
  static const char* value()
  {
    return "mypackage/BadTwoInts";
  }

  static const char* value(const ::mypackage::BadTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::mypackage::BadTwoIntsRequest> should match
// service_traits::MD5Sum< ::mypackage::BadTwoInts >
template<>
struct MD5Sum< ::mypackage::BadTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mypackage::BadTwoInts >::value();
  }
  static const char* value(const ::mypackage::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypackage::BadTwoIntsRequest> should match
// service_traits::DataType< ::mypackage::BadTwoInts >
template<>
struct DataType< ::mypackage::BadTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::mypackage::BadTwoInts >::value();
  }
  static const char* value(const ::mypackage::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mypackage::BadTwoIntsResponse> should match
// service_traits::MD5Sum< ::mypackage::BadTwoInts >
template<>
struct MD5Sum< ::mypackage::BadTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mypackage::BadTwoInts >::value();
  }
  static const char* value(const ::mypackage::BadTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypackage::BadTwoIntsResponse> should match
// service_traits::DataType< ::mypackage::BadTwoInts >
template<>
struct DataType< ::mypackage::BadTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::mypackage::BadTwoInts >::value();
  }
  static const char* value(const ::mypackage::BadTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPACKAGE_MESSAGE_BADTWOINTS_H
